baseURL               = "https://www.hjcmgzs.xyz/"   # 你的新域名
languageCode          = "zh-CN"
title                 = "WebStack-Hugo 网址导航"
theme                 = "WebStack-Hugo"
preserveTaxonomyNames = true
disablePathToLower    = true
hasCJKLanguage        = true
publishDir            = "public"

[params]
    author        = "占豪杰"
    description   = "占豪杰网址导航"
    defaultTheme  = "light"               # 【修复1】明确指定默认主题
    nightMode     = true                  # 【修复2】必须是 true，按钮才会出来！
    
    upload        = ""
    about         = "https://github.com/shenweiyan/Knowledge-Garden/discussions/10"
    repository    = "https://github.com/shenweiyan/WebStack-Hugo"
    
    enablePreLoad = true
    textPreLoad   = "Hugo 网址导航主题"
    expandSidebar = true                  # 默认是否展开侧边栏
    
    # 这里保持原样，如果 Logo 裂了也建议换成网络链接
    logosPath     = "assets/images/logos"
    defaultLogo   = "assets/images/logos/default.webp"
    
    yiyan         = true
    fancybox      = true

[params.seo]
    baiduhmid       = ''
    baiduSiteVer    = ''
    tj51laid        = ''
    tj51lack        = ''
    GoogleAdsClient = ''

# 天气API Key (如果不需要可以留空，因为我们已经用了 HTML 覆盖大法)
[params.qweather]
    key = ""

[params.images]
    # 【修复3】侧边栏按钮全部换成网络图标，防止因找不到本地图片而“消失”
    # 这是一个向右的小箭头
    logoExpandLight   = "https://cdn-icons-png.flaticon.com/512/271/271228.png"
    logoExpandDark    = "https://cdn-icons-png.flaticon.com/512/271/271228.png"
    
    # 这是一个向左的小箭头
    logoCollapseLight = "https://cdn-icons-png.flaticon.com/512/271/271220.png"
    logoCollapseDark  = "https://cdn-icons-png.flaticon.com/512/271/271220.png"
    
    # 你的网站图标
    favicon           = "https://cdn-icons-png.flaticon.com/128/2215/2215535.png"
    
    # 搜索背景图
    searchImageL      = "assets/images/bg-dna.jpg"
    searchImageD      = "assets/images/bg-dna.jpg"

[markup.goldmark.renderer]
    unsafe = true
